Traceback (most recent call last):
  File "/var/folders/rc/dxry5g156qq44k7fj30r8d300000gp/T/ipykernel_39395/162154560.py", line 3, in <module>
    raise Exception('This is the error message.')
Exception: This is the error message.
